# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: oidc-action
description: |
  An OIDC action for usage with Docker Hub. This exchanges a GitHub ID token for 
  the current action workflow in exchange for a short lived access token to be 
  used with Docker Hub.
author: docker
inputs:
  connection-id:
    description: |
      The connection identifier to use for the OIDC flow. This can be found in
      the management section for OIDC connections.
    required: true
  expires-in:
    description: |
      The number of seconds the token should be valid for. This can be used to
      set a custom expiration time for the token. Value must be a min of 300
      (5 minutes) and a max of 21600 (6 hours). The max is to match the maximum
      allowed by GitHub hosted runners. Default is 300.
  connection_id:
    description: |
      The connection identifier to use for the OIDC flow. This can be found in
      the management section for OIDC connections.
    required: false
    deprecationMessage: |
      The input 'connection_id' is deprecated and will be removed in a future
      release. Please use 'connection-id' instead.
  expires_in:
    description: |
      The number of seconds the token should be valid for. This can be used to
      set a custom expiration time for the token. Value must be a min of 300
      (5 minutes) and a max of 21600 (6 hours). The max is to match the maximum
      allowed by GitHub hosted runners. Default is 300.
    deprecationMessage: |
      The input 'expires_in' is deprecated and will be removed in a future
      release. Please use 'expires-in' instead.

outputs:
  token:
    description: |
      The token that was returned by the OIDC exchange. This can be used as a 
      password to the docker/login-action or as a bearer token for API requests.

runs:
  using: node24
  main: dist/index.js
